"""Reproducible, non-copyrighted audio fixture for the guarded B0 bench test."""
from __future__ import annotations

from dataclasses import asdict, dataclass
from hashlib import sha256
from math import exp, pi, sin
from pathlib import Path
import json
import struct
import wave


@dataclass(frozen=True)
class B0Fixture:
    """A short synthetic click, intended only to prove the transfer path."""

    # Match the DDrum4 SE native playback rate for a transfer-path test that
    # does not silently exercise sample-rate conversion instead.
    sample_rate: int = 44100
    duration_ms: int = 180
    frequency_hz: float = 440.0
    peak: float = 0.75

    def __post_init__(self) -> None:
        if self.sample_rate < 8000 or self.duration_ms < 10 or not 20.0 <= self.frequency_hz <= 4000.0:
            raise ValueError("B0 fixture parameters are outside the supported test range")
        if not 0.01 <= self.peak <= 0.99:
            raise ValueError("peak must be 0.01..0.99")

    @property
    def frame_count(self) -> int:
        return round(self.sample_rate * self.duration_ms / 1000)

    def write_wav(self, path: Path) -> dict[str, object]:
        """Write a deterministic mono PCM WAV; this never opens a MIDI port."""
        if path.exists():
            raise FileExistsError(f"refusing to overwrite fixture: {path}")
        path.parent.mkdir(parents=True, exist_ok=True)
        frames = bytearray()
        for index in range(self.frame_count):
            time_s = index / self.sample_rate
            envelope = exp(-time_s * 24.0)
            value = self.peak * envelope * sin(2.0 * pi * self.frequency_hz * time_s)
            frames.extend(struct.pack("<h", round(max(-1.0, min(1.0, value)) * 32767)))
        with wave.open(str(path), "wb") as output:
            output.setnchannels(1)
            output.setsampwidth(2)
            output.setframerate(self.sample_rate)
            output.writeframes(frames)
        return {
            "schema_version": 1,
            "kind": "ddrum4-b0-synthetic-fixture",
            "path": str(path),
            "sha256": sha256(path.read_bytes()).hexdigest(),
            "audio": {"channels": 1, "sample_width_bits": 16, "frames": self.frame_count, **asdict(self)},
            "license": "CC0-style deterministic synthetic waveform generated by drum-toolchain",
            "hardware_write": False,
        }


def write_fixture_manifest(fixture: B0Fixture, wav_path: Path, manifest_path: Path) -> dict[str, object]:
    """Write adjacent provenance before an eventual manual ddrum4UI import."""
    if manifest_path.exists():
        raise FileExistsError(f"refusing to overwrite fixture manifest: {manifest_path}")
    document = fixture.write_wav(wav_path)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return document


@dataclass(frozen=True)
class B0BuildRecord:
    fixture_manifest: str
    fixture_sha256: str
    sound_path: str
    sound_sha256: str
    encoded_blocks: int

    def to_document(self) -> dict[str, object]:
        return {
            "schema_version": 1,
            "kind": "ddrum4-b0-local-build-record",
            **asdict(self),
            "hardware_transfer": False,
        }

    def write(self, path: Path) -> None:
        if path.exists():
            raise FileExistsError(f"refusing to overwrite B0 build record: {path}")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.to_document(), indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_b0_build(fixture_manifest: Path, sound_path: Path, encoded_blocks: int) -> B0BuildRecord:
    """Verify local provenance and measured encoded size; never sends MIDI."""
    if encoded_blocks < 1:
        raise ValueError("B0 sound must contain at least one encoded block")
    try:
        fixture = json.loads(fixture_manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"cannot read B0 fixture manifest: {error}") from error
    if fixture.get("kind") != "ddrum4-b0-synthetic-fixture" or fixture.get("hardware_write") is not False:
        raise ValueError("fixture manifest is not a local B0 synthetic fixture")
    raw_path = Path(str(fixture.get("path", "")))
    expected_hash = fixture.get("sha256")
    if not raw_path.is_file() or not isinstance(expected_hash, str) or sha256(raw_path.read_bytes()).hexdigest() != expected_hash:
        raise ValueError("B0 fixture audio is missing or no longer matches its manifest hash")
    if sound_path.suffix.lower() not in {".mid", ".midi"} or not sound_path.is_file() or sound_path.stat().st_size == 0:
        raise ValueError("B0 local sound must be a non-empty .mid or .midi file")
    return B0BuildRecord(
        str(fixture_manifest), expected_hash, str(sound_path),
        sha256(sound_path.read_bytes()).hexdigest(), encoded_blocks,
    )
