"""Reproducible, non-copyrighted audio fixture for the guarded B0 bench test."""
from __future__ import annotations

from dataclasses import asdict, dataclass
from hashlib import sha256
from math import exp, pi, sin
from pathlib import Path
import json
import struct
import wave


@dataclass(frozen=True)
class B0Fixture:
    """A short synthetic click, intended only to prove the transfer path."""

    # Match the DDrum4 SE native playback rate for a transfer-path test that
    # does not silently exercise sample-rate conversion instead.
    sample_rate: int = 44100
    duration_ms: int = 180
    frequency_hz: float = 440.0
    peak: float = 0.75

    def __post_init__(self) -> None:
        if self.sample_rate < 8000 or self.duration_ms < 10 or not 20.0 <= self.frequency_hz <= 4000.0:
            raise ValueError("B0 fixture parameters are outside the supported test range")
        if not 0.01 <= self.peak <= 0.99:
            raise ValueError("peak must be 0.01..0.99")

    @property
    def frame_count(self) -> int:
        return round(self.sample_rate * self.duration_ms / 1000)

    def write_wav(self, path: Path) -> dict[str, object]:
        """Write a deterministic mono PCM WAV; this never opens a MIDI port."""
        if path.exists():
            raise FileExistsError(f"refusing to overwrite fixture: {path}")
        path.parent.mkdir(parents=True, exist_ok=True)
        frames = bytearray()
        for index in range(self.frame_count):
            time_s = index / self.sample_rate
            envelope = exp(-time_s * 24.0)
            value = self.peak * envelope * sin(2.0 * pi * self.frequency_hz * time_s)
            frames.extend(struct.pack("<h", round(max(-1.0, min(1.0, value)) * 32767)))
        with wave.open(str(path), "wb") as output:
            output.setnchannels(1)
            output.setsampwidth(2)
            output.setframerate(self.sample_rate)
            output.writeframes(frames)
        return {
            "schema_version": 1,
            "kind": "ddrum4-b0-synthetic-fixture",
            "path": str(path),
            "sha256": sha256(path.read_bytes()).hexdigest(),
            "audio": {"channels": 1, "sample_width_bits": 16, "frames": self.frame_count, **asdict(self)},
            "license": "CC0-style deterministic synthetic waveform generated by drum-toolchain",
            "hardware_write": False,
        }


def write_fixture_manifest(fixture: B0Fixture, wav_path: Path, manifest_path: Path) -> dict[str, object]:
    """Write adjacent provenance before an eventual manual ddrum4UI import."""
    if manifest_path.exists():
        raise FileExistsError(f"refusing to overwrite fixture manifest: {manifest_path}")
    document = fixture.write_wav(wav_path)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return document
