#include <juce_gui_extra/juce_gui_extra.h>
#include <juce_audio_devices/juce_audio_devices.h>
#include "config/ProfileLoader.h"
#include "core/Converter.h"
#include <atomic>
#include <memory>
#include <thread>

namespace {
using namespace ddrum4;
struct MonitorLine { MidiEvent event{}; std::array<MidiEvent, Converter::maxOutputEvents> output{}; uint8_t outputCount{}; };
class MonitorQueue {
 public:
  void push(const MidiEvent& event, const std::array<MidiEvent, Converter::maxOutputEvents>& output, size_t outputCount) noexcept { const auto write=w_.load(std::memory_order_relaxed), next=(write+1)%slots; if(next==r_.load(std::memory_order_acquire)) { dropped_.fetch_add(1,std::memory_order_relaxed); return; } q_[write]={event,output,static_cast<uint8_t>(outputCount)}; w_.store(next,std::memory_order_release); }
  bool pop(MonitorLine& value) noexcept { const auto read=r_.load(std::memory_order_relaxed); if(read==w_.load(std::memory_order_acquire)) return false; value=q_[read]; r_.store((read+1)%slots,std::memory_order_release); return true; }
  uint64_t dropped() const noexcept { return dropped_.load(std::memory_order_relaxed); }
 private: static constexpr uint32_t slots=512; std::array<MonitorLine,slots> q_{}; std::atomic<uint32_t>w_{0},r_{0}; std::atomic<uint64_t>dropped_{0};
};
std::filesystem::path findDefaultProfile() {
  const auto nextToApp=std::filesystem::path(juce::File::getSpecialLocation(juce::File::currentExecutableFile).getParentDirectory().getFullPathName().toStdString())/"config/ddrum4-template.yaml";
  if(std::filesystem::exists(nextToApp)) return nextToApp;
  return std::filesystem::current_path()/"config/ddrum4-template.yaml";
}
class Router final : private juce::MidiInputCallback {
 public:
  Router() { try { profilePath_=findDefaultProfile(); reload(); } catch(const std::exception& e) { error_=e.what(); } }
  ~Router() override { stop(); }
  const Profile* profile() const noexcept { return profile_.get(); }
  Converter* converter() const noexcept { return converter_.get(); }
  const std::filesystem::path& profilePath() const noexcept { return profilePath_; }
  juce::String error() const { return error_; }
  MonitorQueue& monitor() noexcept { return monitor_; }
  bool reload() { stop(); try { auto next=std::make_unique<Profile>(loadProfile(profilePath_)); auto converter=std::make_unique<Converter>(*next); profile_=std::move(next); converter_=std::move(converter); error_.clear(); return true; } catch(const std::exception& e) { error_=e.what(); return false; } }
  bool saveAndReload(const juce::String& text) { stop(); const auto temp=profilePath_.string()+".tmp"; try { juce::File(temp).replaceWithText(text); (void)loadProfile(temp); if(!juce::File(profilePath_.string()).replaceWithText(text)) throw std::runtime_error("impossible d'écrire le profil"); std::filesystem::remove(temp); return reload(); } catch(const std::exception& e) { std::error_code ec; std::filesystem::remove(temp,ec); error_=e.what(); return false; } }
  void start(const juce::String& inputId,const juce::String& outputId) { stop(); if(!profile_){error_="Profil non chargé";return;} error_.clear(); outputOwned_=outputId=="__ddrum4_virtual__"?juce::MidiOutput::createNewDevice(profile_->endpoint):juce::MidiOutput::openDevice(outputId); input_=juce::MidiInput::openDevice(inputId,this); if(!input_||!outputOwned_){error_=outputId=="__ddrum4_virtual__"?"Le backend MIDI ne peut pas créer un port virtuel : utilisez loopMIDI sous Windows.":"Impossible d'ouvrir le port MIDI sélectionné";stop();return;} output_.store(outputOwned_.get(),std::memory_order_release); running_.store(true,std::memory_order_release); input_->start(); }
  void stop() { running_.store(false,std::memory_order_release); if(input_) input_->stop(); output_.store(nullptr,std::memory_order_release); while(callbacks_.load(std::memory_order_acquire)!=0) std::this_thread::yield(); if(converter_) converter_->clearLedger(); input_.reset(); outputOwned_.reset(); }
  void panic() { clearLedgerRequested_.store(true,std::memory_order_release); if(auto* out=output_.load(std::memory_order_acquire)) for(int channel=1;channel<=16;++channel) out->sendMessageNow(juce::MidiMessage::allNotesOff(channel)); }
  bool running() const noexcept { return running_.load(std::memory_order_acquire); }
 private:
  std::filesystem::path profilePath_; std::unique_ptr<Profile> profile_; std::unique_ptr<Converter> converter_; std::unique_ptr<juce::MidiInput> input_; std::unique_ptr<juce::MidiOutput> outputOwned_; std::atomic<juce::MidiOutput*> output_{nullptr}; std::atomic<bool> running_{false}; std::atomic<bool> clearLedgerRequested_{false}; std::atomic<uint32_t> callbacks_{0}; juce::String error_; MonitorQueue monitor_;
  void handleIncomingMidiMessage(juce::MidiInput*,const juce::MidiMessage& m) override {
    if(!running_.load(std::memory_order_acquire)) return; callbacks_.fetch_add(1,std::memory_order_acq_rel); const struct Guard{std::atomic<uint32_t>& n;~Guard(){n.fetch_sub(1,std::memory_order_release);}} guard{callbacks_}; auto* destination=output_.load(std::memory_order_acquire); if(!destination||!converter_||!profile_) return; if(clearLedgerRequested_.exchange(false,std::memory_order_acq_rel)) converter_->clearLedger();
    if(m.isMidiClock()||m.isMidiStart()||m.isMidiStop()||m.isMidiContinue()||m.isActiveSense()) { if(profile_->passRealtime) destination->sendMessageNow(m); return; }
    MidiEvent input{}; input.channel=static_cast<uint8_t>(m.getChannel()); input.timestampUs=static_cast<uint64_t>(juce::Time::getHighResolutionTicks());
    if(m.isNoteOn()) input={MidiType::NoteOn,input.channel,static_cast<uint8_t>(m.getNoteNumber()),static_cast<uint8_t>(m.getVelocity()),input.timestampUs}; else if(m.isNoteOff()) input={MidiType::NoteOff,input.channel,static_cast<uint8_t>(m.getNoteNumber()),0,input.timestampUs}; else if(m.isController()) input={MidiType::ControlChange,input.channel,static_cast<uint8_t>(m.getControllerNumber()),static_cast<uint8_t>(m.getControllerValue()),input.timestampUs}; else if(m.isProgramChange()) input={MidiType::ProgramChange,input.channel,static_cast<uint8_t>(m.getProgramChangeNumber()),0,input.timestampUs}; else if(m.isAftertouch()) input={MidiType::PolyAftertouch,input.channel,static_cast<uint8_t>(m.getNoteNumber()),static_cast<uint8_t>(m.getAfterTouchValue()),input.timestampUs}; else return;
    std::array<MidiEvent,Converter::maxOutputEvents> events{}; const auto n=converter_->process(input,events); monitor_.push(input,events,n);
    for(size_t i=0;i<n;++i) { const auto& e=events[i]; juce::MidiMessage result; switch(e.type){case MidiType::NoteOn:result=juce::MidiMessage::noteOn(e.channel,e.data1,(juce::uint8)e.data2);break;case MidiType::NoteOff:result=juce::MidiMessage::noteOff(e.channel,e.data1);break;case MidiType::ControlChange:result=juce::MidiMessage::controllerEvent(e.channel,e.data1,e.data2);break;case MidiType::PolyAftertouch:result=juce::MidiMessage::aftertouchChange(e.channel,e.data1,e.data2);break;case MidiType::ProgramChange:result=juce::MidiMessage::programChange(e.channel,e.data1);break;default:continue;} destination->sendMessageNow(result); }
  }
};

class MainComponent final : public juce::Component, private juce::Timer {
 public:
  MainComponent() { setSize(920,620); setWantsKeyboardFocus(true); title_.setText("ddrum4 Converter",juce::dontSendNotification); title_.setFont(juce::FontOptions(27.0f,juce::Font::bold)); addAndMakeVisible(title_); for(auto* b:{&performance_,&mapping_,&programs_,&monitorTab_}) { addAndMakeVisible(*b); b->setColour(juce::TextButton::buttonColourId,juce::Colour(0xff303640)); } performance_.onClick=[this]{showPage(0);};mapping_.onClick=[this]{showPage(1);};programs_.onClick=[this]{showPage(2);};monitorTab_.onClick=[this]{showPage(3);}; addAndMakeVisible(status_); addAndMakeVisible(input_);addAndMakeVisible(output_);addAndMakeVisible(start_);addAndMakeVisible(panic_); start_.onClick=[this]{toggle();};panic_.onClick=[this]{router_.panic();}; for(auto& b:kits_){addAndMakeVisible(b);} refreshPorts(); buildEditor(); showPage(0); startTimerHz(20); }
  void paint(juce::Graphics& g) override { g.fillAll(juce::Colour(0xff15171b)); g.setColour(juce::Colour(0xff242a31)); g.fillRoundedRectangle(18,100,getWidth()-36,getHeight()-118,10); }
  void resized() override { title_.setBounds(24,18,300,42); int x=340; for(auto* b:{&performance_,&mapping_,&programs_,&monitorTab_}){b->setBounds(x,24,90,30);x+=94;} status_.setBounds(730,27,170,24); input_.setBounds(35,118,275,32);output_.setBounds(320,118,275,32);start_.setBounds(605,118,105,32);panic_.setBounds(720,118,105,32); for(int i=0;i<3;++i) kits_[i].setBounds(38+i*260,180,245,66); config_.setBounds(36,165,845,330);apply_.setBounds(36,505,140,32);monitor_.setBounds(36,165,845,350); info_.setBounds(36,265,845,190); }
 private:
  Router router_; juce::Label title_,status_,info_; juce::ComboBox input_,output_; juce::TextButton start_{"Démarrer"},panic_{"Panic"},performance_{"Jeu"},mapping_{"Mapping"},programs_{"Programmes"},monitorTab_{"Monitor"},apply_{"Appliquer YAML"}; std::array<juce::TextButton,3> kits_{}; juce::TextEditor config_,monitor_; int page_{};
  void buildEditor(){ config_.setMultiLine(true);config_.setColour(juce::TextEditor::backgroundColourId,juce::Colour(0xff101216));config_.setText(juce::File(router_.profilePath().string()).loadFileAsString(),false);addAndMakeVisible(config_);apply_.onClick=[this]{ if(router_.saveAndReload(config_.getText())) refreshPorts(); refresh(); };addAndMakeVisible(apply_); monitor_.setMultiLine(true);monitor_.setReadOnly(true);monitor_.setColour(juce::TextEditor::backgroundColourId,juce::Colour(0xff101216));addAndMakeVisible(monitor_);addAndMakeVisible(info_); }
  void showPage(int next){page_=next; const bool play=page_==0, edit=page_==1, prog=page_==2, mon=page_==3; input_.setVisible(play);output_.setVisible(play);start_.setVisible(play);panic_.setVisible(play); for(auto& b:kits_)b.setVisible(play||prog);config_.setVisible(edit);apply_.setVisible(edit);monitor_.setVisible(mon);info_.setVisible(play||prog); refresh(); }
  void refreshPorts(){ const auto selectedIn=input_.getText(),selectedOut=output_.getText(); input_.clear();output_.clear();int id=1;for(const auto& d:juce::MidiInput::getAvailableDevices())input_.addItem(d.name,id++);output_.addItem("Créer port virtuel : "+juce::String(router_.profile()?router_.profile()->endpoint:"ddrum_converted"),1);id=2;for(const auto& d:juce::MidiOutput::getAvailableDevices())output_.addItem(d.name,id++);const auto* p=router_.profile(); auto choose=[](juce::ComboBox& box,const juce::String& old,const std::string& match){for(int i=0;i<box.getNumItems();++i)if(box.getItemText(i)==old||box.getItemText(i).containsIgnoreCase(match)){box.setSelectedItemIndex(i);return;}if(box.getNumItems())box.setSelectedItemIndex(0);};choose(input_,selectedIn,p?p->inputPortMatch:"");choose(output_,selectedOut,p?p->endpoint:""); }
  void toggle(){if(router_.running())router_.stop();else {const auto in=juce::MidiInput::getAvailableDevices(),out=juce::MidiOutput::getAvailableDevices();const int ii=input_.getSelectedItemIndex(),oi=output_.getSelectedItemIndex();if(ii>=0&&ii<(int)in.size()&&oi>=0)router_.start(in[(size_t)ii].identifier,oi==0?"__ddrum4_virtual__":(oi-1<(int)out.size()?out[(size_t)(oi-1)].identifier:juce::String{}));}refresh();}
  void refresh(){const auto* p=router_.profile();const auto* c=router_.converter();const auto active=c?c->activeKit():0;for(size_t i=0;i<kits_.size();++i){juce::String label="—";if(p&&i<p->kits.size()){label=p->kits[i].label;for(const auto& binding:p->programs)if(binding.kitIndex==i){label+="  · PC "+juce::String(binding.program);break;}}kits_[i].setButtonText(label);kits_[i].onClick=[this,i]{if(auto*c=router_.converter())c->selectKit(i,"UI");};kits_[i].setEnabled(p&&i<p->kits.size());}status_.setText(router_.running()?"● CONNECTÉ":"● ARRÊTÉ",juce::dontSendNotification);start_.setButtonText(router_.running()?"Arrêter":"Démarrer");if(p&&c) { juce::String detail="Kit actif : "; detail+=juce::String(p->kits[active].label); detail+="  · origine : "; detail+=c->lastProgramOrigin(); detail+="\nProfil : "; detail+=juce::String(router_.profilePath().string()); detail+="\n"; detail+=router_.error().isEmpty()?"Choisissez le ddrum4 en entrée et le port virtuel vu par SD3 / DrumGizmo.":router_.error(); info_.setText(detail,juce::dontSendNotification); }}
  void timerCallback() override {MonitorLine line;bool changed=false;while(router_.monitor().pop(line)){juce::String text="IN ch"+juce::String(line.event.channel)+" d"+juce::String(line.event.data1)+" v"+juce::String(line.event.data2)+"  | OUT ";for(uint8_t i=0;i<line.outputCount;++i){const auto&e=line.output[i];text+="ch"+juce::String(e.channel)+" d"+juce::String(e.data1)+" v"+juce::String(e.data2)+(i+1<line.outputCount?" · ":"");}if(line.outputCount==0)text+="filtré";monitor_.moveCaretToEnd();monitor_.insertTextAtCaret(text+"\n");changed=true;}if(changed&&monitor_.getTotalNumChars()>24000)monitor_.setText(monitor_.getTextInRange({monitor_.getTotalNumChars()-18000,18000}),false);refresh();}
};
class App final:public juce::JUCEApplication{public:const juce::String getApplicationName()override{return "ddrum4 Converter";}const juce::String getApplicationVersion()override{return "0.2.0";}void initialise(const juce::String&)override{window_=std::make_unique<Window>(getApplicationName(),std::make_unique<MainComponent>(),*this);}void shutdown()override{window_.reset();}private:class Window final:public juce::DocumentWindow{public:Window(const juce::String& name,std::unique_ptr<juce::Component> content,App& app):DocumentWindow(name,juce::Colour(0xff15171b),allButtons),app_(app){setUsingNativeTitleBar(true);setContentOwned(content.release(),true);centreWithSize(getWidth(),getHeight());setVisible(true);}void closeButtonPressed()override{app_.systemRequestedQuit();}App&app_;};std::unique_ptr<Window>window_;};
}
START_JUCE_APPLICATION(App)
