// Generated by tools/generate_mapping.py; do not edit manually.
// Routing contract SHA-256: e84d9ea5485d8b1bc5862c28762165324aad934ca87d3dc52ba755059fea1a5f
#pragma once
#include "DdrumBridge.h"

constexpr uint8_t DDRUM_OUTPUT_CHANNEL = 12;
const uint8_t RELAY_PROGRAM_CHANNELS[] = {12};
constexpr size_t RELAY_PROGRAM_CHANNEL_COUNT = sizeof(RELAY_PROGRAM_CHANNELS) / sizeof(RELAY_PROGRAM_CHANNELS[0]);

const NoteRoute NOTE_ROUTES[] = {
  {12, 17, 18, 1, 127, 1, 127}, // diagnostic.cymb2.second_note_p_branch
  {12, 18, 18, 1, 127, 1, 127}, // diagnostic.cymb2.physical_second_note_p
};
constexpr size_t NOTE_ROUTE_COUNT = sizeof(NOTE_ROUTES) / sizeof(NOTE_ROUTES[0]);

constexpr HihatDirectCc4Config HIHAT_CC4 = {
  12, 4, 4,
  0, 127,
  0, 127,
  false
};
