// Generated by tools/generate_mapping.py; do not edit manually.
// Routing contract SHA-256: e5d9a4e1ed1f2437ec72d7822063f13d12c84797c5c29773a758a0634fa43082
#pragma once
#include "DdrumBridge.h"

constexpr uint8_t DDRUM_OUTPUT_CHANNEL = 12;
const uint8_t RELAY_PROGRAM_CHANNELS[] = {12};
constexpr size_t RELAY_PROGRAM_CHANNEL_COUNT = sizeof(RELAY_PROGRAM_CHANNELS) / sizeof(RELAY_PROGRAM_CHANNELS[0]);

const NoteRoute NOTE_ROUTES[] = {
  {12, 17, 18, 1, 127, 110, 110}, // diagnostic.cymb2.second_note_p_branch
};
constexpr size_t NOTE_ROUTE_COUNT = sizeof(NOTE_ROUTES) / sizeof(NOTE_ROUTES[0]);

constexpr HihatDirectCc4Config HIHAT_CC4 = {
  12, 4, 4,
  0, 127,
  0, 127,
  false
};
