"""Strict domain model for the versioned ``rig-project/v1`` contract."""
from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
from pathlib import Path
from typing import Any, Mapping

import yaml

from .validation import validate_document


class RigProjectError(ValueError):
    """Raised when a rig project is invalid or cannot be read."""


def _schema_path() -> Path:
    for parent in Path(__file__).resolve().parents:
        candidate = parent / "contracts" / "schemas" / "rig-project.schema.json"
        if candidate.is_file():
            return candidate
    raise RuntimeError("rig-project.schema.json is not available")


@dataclass(frozen=True)
class Source:
    identifier: str
    endpoint: str
    channel: int
    primary: str
    connection_profile: str | None


@dataclass(frozen=True)
class SourceDecoder:
    source: str
    message_type: str
    physical: str
    match: Mapping[str, Any]
    emit: Mapping[str, Any]


@dataclass(frozen=True)
class LogicalRouteVariant:
    """One logical target selected by an optional immutable state predicate."""

    logical_target: str
    predicates: Mapping[str, int]


@dataclass(frozen=True)
class DdrumStateAction:
    """One declared native DDrum4 action used to reconcile a logical scene.

    SysEx is deliberately data-only: the project must carry a captured,
    reviewed payload and its evidence status.  It is never inferred from a
    scene name or generated by the domain layer.
    """

    action_type: str
    status: str
    channel: int | None = None
    program: int | None = None
    data: tuple[int, ...] = ()
    when: Mapping[str, int] = field(default_factory=dict)
    description: str | None = None


@dataclass(frozen=True)
class Ddrum4BankFacts:
    """Verified identity/address facts for a bank linked from a rig project."""

    manifest: Path
    sha256: str
    bank_id: str
    midi_channel: int
    playable_notes: tuple[int, ...]


def logical_route_variants(value: object) -> tuple[LogicalRouteVariant, ...]:
    """Normalise a legacy fixed route or its Scene/VP variant list."""
    if isinstance(value, str):
        return (LogicalRouteVariant(value, {}),)
    if not isinstance(value, list):
        _fail("logical route must be a target id or a list of variants")
    variants: list[LogicalRouteVariant] = []
    for item in value:
        if not isinstance(item, Mapping) or not isinstance(item.get("logical_target"), str):
            _fail("logical route variant needs logical_target")
        when = item.get("when", {})
        if not isinstance(when, Mapping):
            _fail("logical route variant when must be a mapping")
        variants.append(LogicalRouteVariant(item["logical_target"], dict(when)))
    return tuple(variants)


@dataclass(frozen=True)
class RigProject:
    path: Path
    raw: Mapping[str, Any]
    project: str
    rig: str
    deployment: str
    ddrum4_output_channel: int
    control_bus: Mapping[str, Any] | None
    ddrum4_bank: Mapping[str, Any] | None
    ddrum4_bank_facts: Ddrum4BankFacts | None
    sources: Mapping[str, Source]
    connection_profiles: Mapping[str, Mapping[str, Any]]
    source_decoders: tuple[SourceDecoder, ...]
    physical_events: tuple[str, ...]
    scenes: tuple[str, ...]
    variables: tuple[str, ...]
    defaults: Mapping[str, Any]
    logical_control_protocol: Mapping[str, Mapping[str, Any]]
    logical_routes: Mapping[str, Mapping[str, Any]]
    renderers: Mapping[str, Mapping[str, Mapping[str, Any]]]
    native_control_map: Mapping[str, Mapping[str, Any]]
    ddrum_state_actions: Mapping[str, tuple[DdrumStateAction, ...]]
    policies: Mapping[str, Any]


def _fail(message: str) -> None:
    raise RigProjectError(message)


def _bank_facts(project_path: Path, reference: Mapping[str, Any] | None,
                output_channel: int) -> Ddrum4BankFacts | None:
    if reference is None:
        return None
    manifest = (project_path.parent / reference["manifest"]).resolve()
    try:
        payload = manifest.read_bytes()
        document = yaml.safe_load(payload.decode("utf-8"))
    except OSError as error:
        _fail(f"ddrum4_bank manifest cannot be read: {manifest}")
    except (UnicodeDecodeError, yaml.YAMLError) as error:
        _fail(f"ddrum4_bank manifest cannot be parsed: {manifest}")
    if not isinstance(document, Mapping) or not isinstance(document.get("bank"), Mapping):
        _fail("ddrum4_bank manifest must contain a bank mapping")
    bank = document["bank"]
    bank_id, channel = bank.get("id"), bank.get("midi_channel")
    if not isinstance(bank_id, str) or not isinstance(channel, int):
        _fail("ddrum4_bank manifest needs bank.id and bank.midi_channel")
    if channel != output_channel:
        _fail("ddrum4_bank midi_channel must equal ddrum4_output_channel")
    digest = hashlib.sha256(payload).hexdigest()
    if reference.get("bank_id") not in {None, bank_id}:
        _fail("ddrum4_bank bank_id does not match its manifest")
    if reference.get("sha256") not in {None, digest}:
        _fail("ddrum4_bank sha256 does not match its manifest")
    sounds = document.get("sounds")
    if not isinstance(sounds, list) or not sounds:
        _fail("ddrum4_bank manifest needs declared sounds")
    notes: set[int] = set()
    for index, sound in enumerate(sounds):
        if not isinstance(sound, Mapping) or not isinstance(sound.get("note_base"), int) or not isinstance(sound.get("note_p"), int):
            _fail(f"ddrum4_bank sound {index + 1} needs note_base and note_p")
        base, width = sound["note_base"], sound["note_p"]
        if not 0 <= base <= 127 or not 1 <= width <= 128 - base:
            _fail(f"ddrum4_bank sound {index + 1} has invalid NOTE#/NOTE P range")
        notes.update(range(base, base + width))
    return Ddrum4BankFacts(manifest, digest, bank_id, channel, tuple(sorted(notes)))


def _validate_semantics(document: Mapping[str, Any]) -> None:
    sources = document["sources"]
    profiles = document["connection_profiles"]
    source_addresses: set[tuple[str, int]] = set()
    for identifier, source in sources.items():
        profile = source.get("connection_profile")
        if profile is not None and profile not in profiles:
            _fail(f"source {identifier}: unknown connection profile {profile!r}")
        address = (source["endpoint"], source["channel"])
        if address in source_addresses:
            _fail(f"source {identifier}: ambiguous source endpoint/channel")
        source_addresses.add(address)

    deployment = document["deployment"]
    output_channel = document["ddrum4_output_channel"]
    if deployment == "live":
        simulated = [name for name, source in sources.items()
                     if source["endpoint"].upper().startswith("SIM_") or "MEASURE_ME" in source["endpoint"]]
        if simulated:
            _fail(f"live deployment cannot use simulated or unresolved endpoint {simulated[0]!r}")
        ddrum = sources.get("ddrum4")
        if ddrum is None:
            _fail("live deployment must declare the ddrum4 source")
        if ddrum["channel"] != output_channel:
            _fail("live ddrum4 source channel must equal ddrum4_output_channel")
        control_bus = document.get("control_bus")
        if control_bus is not None:
            if control_bus["status"] != "user-confirmed":
                _fail("live control_bus must be user-confirmed")
            if control_bus["endpoint"].upper().startswith("SIM_") or "MEASURE_ME" in control_bus["endpoint"]:
                _fail("live control_bus cannot use a simulated or unresolved endpoint")

    physical_events = set(document["physical_events"])
    decoder_keys: set[tuple[Any, ...]] = set()
    note_intervals: dict[str, list[tuple[int, int]]] = {}
    poly_aftertouch_sources: set[str] = set()
    emitted: set[str] = set()
    for index, decoder in enumerate(document["source_decoders"]):
        match = decoder["match"]
        emit = decoder["emit"]
        source = match["source"]
        message_type = match["type"]
        if source not in sources:
            _fail(f"source_decoders[{index}]: unknown source {source!r}")
        if message_type == "note" and set(match) != {"source", "type", "note"}:
            _fail(f"source_decoders[{index}]: note requires exactly match.note")
        if message_type == "note_range":
            if set(match) != {"source", "type", "note_range"}:
                _fail(f"source_decoders[{index}]: note_range requires exactly match.note_range")
            if match["note_range"][0] > match["note_range"][1]:
                _fail(f"source_decoders[{index}]: note_range must be ascending")
        if message_type == "cc" and set(match) != {"source", "type", "cc"}:
            _fail(f"source_decoders[{index}]: cc requires exactly match.cc")
        if message_type == "poly_aftertouch" and not set(match).issubset({"source", "type", "note", "active_note"}):
            _fail(f"source_decoders[{index}]: invalid poly_aftertouch matcher")
        if message_type in {"note", "note_range"}:
            interval = (match["note"], match["note"]) if message_type == "note" else tuple(match["note_range"])
            for low, high in note_intervals.setdefault(source, []):
                if interval[0] <= high and low <= interval[1]:
                    _fail(f"source_decoders[{index}]: overlapping note decoder")
            note_intervals[source].append(interval)
        if message_type == "poly_aftertouch":
            if source in poly_aftertouch_sources:
                _fail(f"source_decoders[{index}]: ambiguous poly_aftertouch decoder")
            poly_aftertouch_sources.add(source)
        if emit["physical"] not in physical_events:
            _fail(f"source_decoders[{index}]: unknown physical event {emit['physical']!r}")
        expressions = set(emit.get("expressions", []))
        semantic_expressions = expressions & {"openness", "pressure", "position"}
        if message_type in {"cc", "poly_aftertouch"} and len(semantic_expressions) > 1:
            _fail(f"source_decoders[{index}]: CC/poly-aftertouch supports exactly one semantic expression per decoder")
        if message_type == "cc" and ("velocity" in expressions or emit.get("normalize") != "cc7"):
            _fail(f"source_decoders[{index}]: cc must use normalize: cc7 and cannot emit velocity")
        if "position" in expressions and message_type == "note":
            _fail(f"source_decoders[{index}]: exact Note cannot carry position; use a measured range or expression routing")
        if "position" in expressions and message_type == "note_range" and match["note_range"][0] == match["note_range"][1]:
            _fail(f"source_decoders[{index}]: positional note_range needs distinct bounds")
        if message_type == "poly_aftertouch" and "velocity" in expressions:
            _fail(f"source_decoders[{index}]: poly_aftertouch cannot emit velocity")
        if message_type == "poly_aftertouch" and bool(match.get("active_note")) != (emit.get("correlate") == "source_channel_note"):
            _fail(f"source_decoders[{index}]: active_note and correlate: source_channel_note must be declared together")
        key = (source, message_type, tuple(sorted((key, repr(value)) for key, value in match.items() if key != "source")))
        if key in decoder_keys:
            _fail(f"source_decoders[{index}]: ambiguous duplicate decoder")
        decoder_keys.add(key)
        emitted.add(emit["physical"])
    missing = physical_events - emitted
    if missing:
        _fail(f"physical events without decoder: {', '.join(sorted(missing))}")

    state = document["state"]
    scenes, variables, defaults = set(state["scenes"]), set(state["variables"]), state["defaults"]
    if len(scenes) > 128:
        _fail("state supports at most 128 scenes (MIDI Program Change 0..127)")
    if len(variables) > 4:
        _fail("state supports at most 4 variables (MVP logical-control protocol)")
    if defaults.get("scene") not in scenes:
        _fail("state.defaults.scene must name a declared scene")
    if set(defaults) != {"scene", *variables}:
        _fail("state.defaults must define scene and every variable, with no extras")

    protocol = document["logical_control_protocol"]
    if set(protocol) != {"scene", *variables}:
        _fail("logical_control_protocol must cover scene and every state variable")
    if protocol["scene"]["type"] != "program_change" or "cc" in protocol["scene"]:
        _fail("scene control must be program_change without cc")
    cc_numbers: set[int] = set()
    for name in variables:
        control = protocol[name]
        if control["type"] != "cc" or "cc" not in control:
            _fail(f"state variable {name} must use a CC control")
        if control["cc"] in cc_numbers:
            _fail("logical state variables use duplicate CC numbers")
        cc_numbers.add(control["cc"])

    routes = document["logical_routes"]
    if set(routes) != scenes:
        _fail("logical_routes must cover every declared scene and no others")
    logical_sounds: set[str] = set()
    for scene, mappings in routes.items():
        missing = physical_events - set(mappings)
        if missing:
            _fail(f"scene {scene}: physical events without route: {', '.join(sorted(missing))}")
        for physical, value in mappings.items():
            variants = logical_route_variants(value)
            fallback_count = sum(not variant.predicates for variant in variants)
            if fallback_count != 1:
                _fail(f"scene {scene} physical event {physical}: route variants need exactly one fallback")
            conditional = [variant for variant in variants if variant.predicates]
            for variant in conditional:
                unknown = set(variant.predicates) - variables
                if unknown:
                    _fail(f"scene {scene} physical event {physical}: unknown state predicate {sorted(unknown)[0]!r}")
            for index, left in enumerate(conditional):
                for right in conditional[index + 1:]:
                    common = set(left.predicates) & set(right.predicates)
                    if all(left.predicates[name] == right.predicates[name] for name in common):
                        _fail(f"scene {scene} physical event {physical}: overlapping route state predicates")
            logical_sounds.update(variant.logical_target for variant in variants)
    for renderer_name in ("ddrum4", "sd3", "drumgizmo"):
        renderer = document["renderers"][renderer_name]
        missing = logical_sounds - set(renderer)
        if missing:
            _fail(f"renderer {renderer_name}: logical sounds without renderer: {', '.join(sorted(missing))}")

    # Expression routes are intentionally explicit and target-qualified.  A
    # raw CC must never infer a renderer CC from an output note, and an
    # aftertouch route must declare its correlation policy.  The model remains
    # optional while legacy profiles are migrated, but any declared route is
    # complete enough to be compiled and loaded without a fallback.
    expression_routes = document.get("expression_routing", ())
    expression_decoders: dict[tuple[str, str, str], Mapping[str, Any]] = {}
    for decoder in document["source_decoders"]:
        match, emit = decoder["match"], decoder["emit"]
        if match["type"] not in {"cc", "poly_aftertouch"}:
            continue
        for expression in emit.get("expressions", ()):
            if expression in {"openness", "pressure", "position"}:
                key = (match["source"], emit["physical"], expression)
                if key in expression_decoders:
                    _fail(f"expression decoder {key!r} is ambiguous")
                expression_decoders[key] = decoder
    expression_keys: set[tuple[str, str, str]] = set()
    reviewed_ddrum4_hihat_quantizations = 0
    reviewed_drumgizmo_hihat_quantizations = 0
    for index, route in enumerate(expression_routes):
        key = (route["source"], route["physical"], route["expression"])
        if key in expression_keys:
            _fail(f"expression_routing[{index}]: duplicate source/physical/expression route")
        expression_keys.add(key)
        decoder = expression_decoders.get(key)
        if decoder is None:
            _fail(f"expression_routing[{index}]: no matching CC or poly-aftertouch source decoder")
        matcher = decoder["match"]["type"]
        if route["expression"] == "openness" and (matcher != "cc" or route["correlation"] != "none"):
            _fail(f"expression_routing[{index}]: openness requires a CC decoder with correlation: none")
        if route["expression"] == "pressure" and (matcher != "poly_aftertouch" or route["correlation"] != "source_channel_note"):
            _fail(f"expression_routing[{index}]: pressure requires correlated poly-aftertouch")
        for target_name, target in route["targets"].items():
            status, event = target["status"], target["event"]
            event_type = event["type"]
            if status == "unsupported":
                if event_type != "unsupported" or not target.get("reason"):
                    _fail(f"expression_routing[{index}].targets.{target_name}: unsupported target needs reason and event.type: unsupported")
                continue
            if target_name == "drumgizmo":
                if event_type != "quantized_note":
                    _fail(f"expression_routing[{index}].targets.drumgizmo: only quantized_note is representable")
                if status in {"measured", "user-confirmed"}:
                    reviewed_drumgizmo_hihat_quantizations += 1
                    closed, opened = event.get("input_closed"), event.get("input_open")
                    articulations = event.get("articulations")
                    if (not isinstance(closed, int) or not isinstance(opened, int) or
                            not 0 <= closed <= 127 or not 0 <= opened <= 127 or closed == opened):
                        _fail(f"expression_routing[{index}].targets.drumgizmo: reviewed quantization needs distinct measured input_closed/input_open")
                    if not isinstance(articulations, list) or not articulations:
                        _fail(f"expression_routing[{index}].targets.drumgizmo: reviewed quantization needs articulation zones")
                    seen_articulations: set[str] = set()
                    for articulation in articulations:
                        physical = articulation.get("physical") if isinstance(articulation, Mapping) else None
                        notes = articulation.get("notes") if isinstance(articulation, Mapping) else None
                        boundaries = articulation.get("upper_boundaries") if isinstance(articulation, Mapping) else None
                        if physical not in physical_events or physical in seen_articulations:
                            _fail(f"expression_routing[{index}].targets.drumgizmo: invalid or duplicate hihat articulation")
                        seen_articulations.add(physical)
                        if (not isinstance(notes, list) or not 1 <= len(notes) <= 8 or
                                not all(isinstance(note, int) and 0 <= note <= 127 for note in notes) or
                                not isinstance(boundaries, list) or len(boundaries) != len(notes) - 1 or
                                not all(isinstance(boundary, int) and 0 <= boundary <= 127 for boundary in boundaries) or
                                any(boundary >= 127 for boundary in boundaries) or
                                any(right <= left for left, right in zip(boundaries, boundaries[1:]))):
                            _fail(f"expression_routing[{index}].targets.drumgizmo: hihat zone notes/boundaries are invalid")
                        for scene in scenes:
                            variants = logical_route_variants(routes[scene][physical])
                            if not any(document["renderers"]["drumgizmo"][variant.logical_target]["note"] == notes[0]
                                       for variant in variants):
                                _fail(f"expression_routing[{index}].targets.drumgizmo: {physical!r} has no matching renderer base note")
                elif status != "planned":
                    _fail(f"expression_routing[{index}].targets.drumgizmo: quantized_note is planned, measured, or user-confirmed only")
                continue
            if target_name == "ddrum4":
                if event_type != "quantized_note_p":
                    _fail(f"expression_routing[{index}].targets.ddrum4: only planned quantized_note_p is currently representable")
                if status in {"measured", "user-confirmed"}:
                    reviewed_ddrum4_hihat_quantizations += 1
                    closed, opened = event.get("input_closed"), event.get("input_open")
                    articulations = event.get("articulations")
                    if not isinstance(closed, int) or not isinstance(opened, int) or not 0 <= closed <= 127 or not 0 <= opened <= 127 or closed == opened:
                        _fail(f"expression_routing[{index}].targets.ddrum4: reviewed quantization needs distinct measured input_closed/input_open")
                    if not isinstance(articulations, list) or not articulations:
                        _fail(f"expression_routing[{index}].targets.ddrum4: reviewed quantization needs articulation zones")
                    seen_articulations: set[str] = set()
                    for articulation in articulations:
                        physical = articulation.get("physical") if isinstance(articulation, Mapping) else None
                        notes = articulation.get("notes") if isinstance(articulation, Mapping) else None
                        boundaries = articulation.get("upper_boundaries") if isinstance(articulation, Mapping) else None
                        if physical not in physical_events or physical in seen_articulations:
                            _fail(f"expression_routing[{index}].targets.ddrum4: invalid or duplicate hihat articulation")
                        seen_articulations.add(physical)
                        if (not isinstance(notes, list) or not 1 <= len(notes) <= 8 or
                                not all(isinstance(note, int) and 0 <= note <= 127 for note in notes) or
                                not isinstance(boundaries, list) or len(boundaries) != len(notes) - 1 or
                                not all(isinstance(boundary, int) and 0 <= boundary <= 127 for boundary in boundaries) or
                                any(boundary >= 127 for boundary in boundaries) or
                                any(right <= left for left, right in zip(boundaries, boundaries[1:]))):
                            _fail(f"expression_routing[{index}].targets.ddrum4: hihat zone notes/boundaries are invalid")
                elif status != "planned":
                    _fail(f"expression_routing[{index}].targets.ddrum4: quantized_note_p is planned, measured, or user-confirmed only")
                continue
            if route["expression"] != "openness" or event_type != "cc" or event.get("transform") != "passthrough":
                _fail(f"expression_routing[{index}].targets.sd3: the implemented vertical is openness -> passthrough CC")
            if status not in {"measured", "user-confirmed"}:
                _fail(f"expression_routing[{index}].targets.sd3: a live CC target must be measured or user-confirmed")
            if not isinstance(event.get("channel"), int) or not isinstance(event.get("cc"), int):
                _fail(f"expression_routing[{index}].targets.sd3: CC event needs channel and cc")
            for scene in scenes:
                for variant in logical_route_variants(routes[scene][route["physical"]]):
                    renderer = document["renderers"]["sd3"][variant.logical_target]
                    if renderer.get("channel", 10) != event["channel"] or renderer.get("cc") != event["cc"]:
                        _fail(f"expression_routing[{index}].targets.sd3: renderer {variant.logical_target!r} must declare the same channel and cc")
    if reviewed_ddrum4_hihat_quantizations > 1:
        _fail("only one reviewed DDrum4 hi-hat quantization is supported by the Uno profile")
    if reviewed_drumgizmo_hihat_quantizations > 1:
        _fail("only one reviewed DrumGizmo hi-hat quantization is supported by the runtime profile")

    # A DrumGizmo midimap is one MIDI-note address per logical sound. The
    # all-zero M1 fixture is explicitly unresolved and therefore exempt until
    # measured values replace the endpoint placeholders.
    unresolved = any("MEASURE_ME" in source["endpoint"] for source in sources.values())
    if not unresolved:
        notes: dict[int, str] = {}
        for logical, renderer in document["renderers"]["drumgizmo"].items():
            note = renderer["note"]
            if note in notes:
                _fail(f"drumgizmo renderer: note {note} maps both {notes[note]!r} and {logical!r}")
            notes[note] = logical

    control_targets = {"scene", *variables}
    native_keys: list[tuple[str | None, int, str, int]] = []
    for name, native in document["native_control_map"].items():
        if native["decode_to"] not in control_targets:
            _fail(f"native control {name}: unknown state target {native['decode_to']!r}")
        if native["decode_to"] == "scene" and native.get("value") not in range(len(scenes)):
            _fail(f"native control {name}: scene value must be an index of declared state.scenes")
        if native.get("channel") in (14, 15):
            _fail(f"native control {name}: channels 14 and 15 are reserved for logical control")
        native_type = native["type"]
        if native_type == "cc" and "cc" not in native:
            _fail(f"native control {name}: CC control requires cc")
        if native_type == "note" and "note" not in native:
            _fail(f"native control {name}: note control requires note")
        if native_type == "program_change" and ("cc" in native or "note" in native or "program" not in native):
            _fail(f"native control {name}: program_change requires program and cannot declare cc or note")
        if native_type == "cc" and "note" in native:
            _fail(f"native control {name}: CC control cannot declare note")
        if native_type == "note" and "cc" in native:
            _fail(f"native control {name}: note control cannot declare cc")
        source = native.get("source")
        if source is not None:
            if source not in sources:
                _fail(f"native control {name}: unknown source {source!r}")
            if native["channel"] != sources[source]["channel"]:
                _fail(f"native control {name}: channel must match source {source!r}")
        address = native.get("cc") if native_type == "cc" else native.get("note") if native_type == "note" else native["program"]
        key = (source, native["channel"], native_type, address)
        for existing_source, channel, existing_type, existing_address in native_keys:
            if (channel, existing_type, existing_address) == key[1:] and (source is None or existing_source is None or source == existing_source):
                _fail(f"native control {name}: overlaps another native control")
        native_keys.append(key)

    state_actions = document.get("ddrum_state_actions", {})
    if not isinstance(state_actions, Mapping):
        _fail("ddrum_state_actions must be a mapping when declared")
    unknown_action_scenes = set(state_actions) - scenes
    if unknown_action_scenes:
        _fail(f"ddrum_state_actions has unknown scene {sorted(unknown_action_scenes)[0]!r}")
    for scene, actions in state_actions.items():
        if not isinstance(actions, list):
            _fail(f"ddrum_state_actions.{scene} must be a list")
        for index, action in enumerate(actions):
            if not isinstance(action, Mapping):
                _fail(f"ddrum_state_actions.{scene}[{index}] must be a mapping")
            kind = action.get("type")
            status = action.get("status")
            if kind not in {"program_change", "sysex"}:
                _fail(f"ddrum_state_actions.{scene}[{index}] has unsupported type")
            if status not in {"measured", "user-confirmed", "planned"}:
                _fail(f"ddrum_state_actions.{scene}[{index}] has invalid status")
            if kind == "program_change":
                if set(action) - {"type", "status", "channel", "program", "when", "description"}:
                    _fail(f"ddrum_state_actions.{scene}[{index}] has invalid Program Change fields")
                if not isinstance(action.get("channel"), int) or not 1 <= action["channel"] <= 16:
                    _fail(f"ddrum_state_actions.{scene}[{index}] Program Change needs channel 1..16")
                if not isinstance(action.get("program"), int) or not 0 <= action["program"] <= 127:
                    _fail(f"ddrum_state_actions.{scene}[{index}] Program Change needs program 0..127")
            else:
                if set(action) - {"type", "status", "data", "when", "description"}:
                    _fail(f"ddrum_state_actions.{scene}[{index}] has invalid SysEx fields")
                data = action.get("data")
                if not isinstance(data, list) or not data or any(not isinstance(byte, int) or not 0 <= byte <= 127 for byte in data):
                    _fail(f"ddrum_state_actions.{scene}[{index}] SysEx needs non-empty 7-bit data")
            when = action.get("when", {})
            if not isinstance(when, Mapping) or not set(when).issubset(variables):
                _fail(f"ddrum_state_actions.{scene}[{index}] has unknown state predicate")
            if any(not isinstance(value, int) or not 0 <= value <= 127 for value in when.values()):
                _fail(f"ddrum_state_actions.{scene}[{index}] has invalid state predicate value")


def load_rig_project(path: Path) -> RigProject:
    """Load and strictly validate a ``rig-project/v1`` YAML document."""
    try:
        document = yaml.safe_load(path.read_text(encoding="utf-8"))
    except OSError as error:
        raise RigProjectError(f"cannot read {path}: {error}") from error
    except yaml.YAMLError as error:
        raise RigProjectError(f"invalid YAML in {path}: {error}") from error
    try:
        validate_document(document, _schema_path())
    except ValueError as error:
        raise RigProjectError(str(error)) from error
    if not isinstance(document, dict):  # Kept explicit for static typing and future schema changes.
        _fail("rig project root must be a mapping")
    _validate_semantics(document)
    bank_facts = _bank_facts(path, document.get("ddrum4_bank"), document["ddrum4_output_channel"])
    if bank_facts is not None:
        invalid_notes = sorted({renderer["note"] for renderer in document["renderers"]["ddrum4"].values()
                                if renderer["note"] not in bank_facts.playable_notes})
        if invalid_notes:
            _fail(f"ddrum4 renderer note {invalid_notes[0]} is outside the linked bank NOTE#/NOTE P ranges")
    state = document["state"]
    source_objects = {name: Source(name, value["endpoint"], value["channel"], value["primary"], value.get("connection_profile")) for name, value in document["sources"].items()}
    decoders = tuple(SourceDecoder(item["match"]["source"], item["match"]["type"], item["emit"]["physical"], item["match"], item["emit"]) for item in document["source_decoders"])
    actions: dict[str, tuple[DdrumStateAction, ...]] = {}
    for scene, rows in document.get("ddrum_state_actions", {}).items():
        actions[scene] = tuple(DdrumStateAction(
            action_type=row["type"], status=row["status"], channel=row.get("channel"),
            program=row.get("program"), data=tuple(row.get("data", ())), when=dict(row.get("when", {})), description=row.get("description"),
        ) for row in rows)
    return RigProject(path, document, document["project"], document["rig"], document["deployment"], document["ddrum4_output_channel"], document.get("control_bus"), document.get("ddrum4_bank"), bank_facts, source_objects, document["connection_profiles"], decoders, tuple(document["physical_events"]), tuple(state["scenes"]), tuple(state["variables"]), state["defaults"], document["logical_control_protocol"], document["logical_routes"], document["renderers"], document["native_control_map"], actions, document["policies"])
