#!/usr/bin/env python3
"""Generate include/generated_mapping.h from a ddrum4 hybrid-kit manifest."""
from __future__ import annotations

import argparse
from hashlib import sha256
from pathlib import Path
import sys

import yaml


POSITION_INDEX = {
    1: {1: 0},
    2: {1: 0, 5: 1},
    4: {1: 0, 3: 1, 5: 2, 7: 3},
    8: {position: position - 1 for position in range(1, 9)},
}


def integer(value, label, minimum, maximum):
    if not isinstance(value, int) or not minimum <= value <= maximum:
        raise ValueError(f"{label} must be an integer from {minimum} to {maximum}")
    return value


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--output", type=Path, default=Path("include/generated_mapping.h"))
    args = parser.parse_args()
    try:
        manifest_bytes = args.manifest.read_bytes()
        document = yaml.safe_load(manifest_bytes.decode("utf-8"))
        manifest_hash = sha256(manifest_bytes).hexdigest()
        midi = document["midi"]
        sources = midi["sources"]
        out_channel = integer(midi["ddrum_output_channel"], "midi.ddrum_output_channel", 1, 16)
        if not isinstance(sources, dict) or not sources:
            raise ValueError("midi.sources must contain at least one named source")
        source_channels = {}
        for source_name, source in sources.items():
            source_channels[source_name] = integer(source["channel"], f"{source_name} channel", 1, 16)
        hihat = document["hihat"]
        if hihat["mode"] != "direct_cc4":
            raise ValueError("only hihat.mode=direct_cc4 is supported in this firmware version")
        hihat_source = hihat.get("source", "edrumin")
        if hihat_source not in source_channels:
            raise ValueError(f"hihat source {hihat_source!r} is not declared in midi.sources")
        routes = []
        # Support the original hihat-specific schema as well as the project
        # manifest's resolved targets.  A target note is authoritative: it is
        # what ddrum4 will receive after the planned sound was installed.
        if "articulations" in hihat:
            hihat_channel = document["ddrum_channels"]["hihat"]
            note_base = integer(hihat_channel["note_base"], "hihat note_base", 0, 127)
            note_p = integer(hihat_channel["note_p"], "hihat note_p", 1, 8)
            if note_p not in POSITION_INDEX:
                raise ValueError("hihat note_p must be one of 1, 2, 4, 8")
            for name, articulation in hihat["articulations"].items():
                input_note = integer(articulation["input_note"], f"hihat {name} input_note", 0, 127)
                position = integer(articulation["position"], f"hihat {name} position", 1, 8)
                if position not in POSITION_INDEX[note_p]:
                    raise ValueError(f"hihat {name}: position {position} is impossible with Note P={note_p}")
                routes.append((source_channels[hihat_source], input_note, note_base + POSITION_INDEX[note_p][position], 1, 127, 1, 127, f"hihat_{name}"))
        for route in document.get("routes", []):
            # Generic routes deliberately use a fully resolved output note until
            # all ddrum channel layouts are added to the generator.
            source = route["source"]
            if source not in source_channels:
                raise ValueError(f"route source {source!r} is not declared in midi.sources")
            channel = source_channels[source]
            target = route.get("target", route)
            velocity = target.get("velocity", {})
            if not isinstance(velocity, dict):
                raise ValueError("route target.velocity must be a mapping")
            route_name = route.get("id", route.get("identifier", "route"))
            if route.get("sound_id"):
                route_name = f"{route['sound_id']} / {route_name}"
            routes.append((channel, integer(route["input_note"], "route input_note", 0, 127),
                           integer(target["output_note"], "route output_note", 0, 127),
                           integer(velocity.get("input_min", 1), "velocity input_min", 1, 127),
                           integer(velocity.get("input_max", 127), "velocity input_max", 1, 127),
                           integer(velocity.get("output_min", 1), "velocity output_min", 1, 127),
                           integer(velocity.get("output_max", 127), "velocity output_max", 1, 127),
                           route_name))
        if len({(item[0], item[1]) for item in routes}) != len(routes):
            raise ValueError("duplicate source channel/note route")
        if any(item[2] > 127 for item in routes):
            raise ValueError("output note exceeds MIDI range")

        lines = [
            "// Generated by tools/generate_mapping.py; do not edit manually.",
            f"// Routing contract SHA-256: {manifest_hash}",
            "#pragma once",
            "#include \"DdrumBridge.h\"",
            "",
            f"constexpr uint8_t DDRUM_OUTPUT_CHANNEL = {out_channel};",
            "const uint8_t RELAY_PROGRAM_CHANNELS[] = {" + ", ".join(str(channel) for channel in sorted(set(source_channels.values()))) + "};",
            "constexpr size_t RELAY_PROGRAM_CHANNEL_COUNT = sizeof(RELAY_PROGRAM_CHANNELS) / sizeof(RELAY_PROGRAM_CHANNELS[0]);",
            "",
            "const NoteRoute NOTE_ROUTES[] = {",
        ]
        lines.extend(f"  {{{channel}, {source_note}, {target_note}, {input_min}, {input_max}, {output_min}, {output_max}}}, // {name}"
                     for channel, source_note, target_note, input_min, input_max, output_min, output_max, name in routes)
        lines.extend([
            "};",
            "constexpr size_t NOTE_ROUTE_COUNT = sizeof(NOTE_ROUTES) / sizeof(NOTE_ROUTES[0]);",
            "",
            "constexpr HihatDirectCc4Config HIHAT_CC4 = {",
            f"  {source_channels[hihat_source]}, {integer(hihat['input_cc'], 'input_cc', 0, 127)}, {integer(hihat['output_cc'], 'output_cc', 0, 127)},",
            f"  {integer(hihat['input_closed'], 'input_closed', 0, 127)}, {integer(hihat['input_open'], 'input_open', 0, 127)},",
            f"  {integer(hihat['output_closed'], 'output_closed', 0, 127)}, {integer(hihat['output_open'], 'output_open', 0, 127)},",
            f"  {'true' if hihat.get('invert', False) else 'false'}",
            "};",
            "",
        ])
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text("\n".join(lines), encoding="utf-8")
    except (KeyError, TypeError, ValueError, yaml.YAMLError) as error:
        print(f"mapping generation failed: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
